# Generated by Django 5.2.7 on 2025-10-30 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('budget_code', models.CharField(max_length=50, unique=True)),
                ('approved_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fiscal_year', models.CharField(max_length=9)),
                ('date_approved', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'IDP Project',
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('idp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compliance.idp')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_number', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField()),
                ('date_drafted', models.DateField(auto_now_add=True)),
                ('rigged_keywords_found', models.JSONField(blank=True, default=list)),
                ('requisition', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='compliance.requisition')),
            ],
        ),
    ]
